const RESPONSE_CODE = {
    DEFAULT: 'SUCCESS',
    LOGIN: 'LOGIN',
    OTP: 'OTP_VERIFIED',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    ERROR: 'ERROR',
    ALERTS: 'ALERTS',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    NOT_VERIFIED: 'NOT_VERIFIED',
    CHAT_FOUND: 'CHAT_FOUND',
    CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
}

module.exports = {
    RESPONSE_CODE,
}
